require('minitest/autorun')
require('minitest/rg')
require_relative('../models/book')
require_relative('../models/author')

class BookTest < MiniTest::Test

  def setup
    @author1 = Author.new({'name' => 'Harper Lee'})
    @author2 = Author.new({'name' => 'George Orwell'})
    @author3 = Author.new({'name' => 'Charles Dickens'})
    @book1 = Book.new({'title' => 'To Kill a Mockingbird',
      'buying_price'=> 5, 'selling_price' => 8, 'author_id' => @author1.id })
    @book2 = Book.new({'title' => 'Great Expectations', 'buying_price' => 6,
      'selling_price' => 8, 'author_id' => @author3.id })
  end


  def test_book_title
    assert_equal('To Kill a Mockingbird', @book1.title)
  end

  def test_book_buying_price
    assert_equal(5, @book1.buying_price)
  end

  def test_book_selling_price
    assert_equal(8, @book2.selling_price)
  end

  # Te below method worked to check if id reader was working, by
# predicitng the id which would be generated by the database.

  # def test_book_id
  #   @book1.save
  #   assert_equal("15", @book1.id)
  # end
end
